[package]
name = "solana-serialize-utils"
description = "Solana helpers for reading and writing bytes."
documentation = "https://docs.rs/solana-serialize-utils"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
solana-instruction-error = { workspace = true }
solana-pubkey = { workspace = true, default-features = false }
solana-sanitize = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
borsh = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
solana-pubkey = { workspace = true, default-features = false, features = [
    "borsh",
    "serde",
] }
