[package]
name = "solana-derivation-path"
description = "Solana BIP44 derivation paths."
documentation = "https://docs.rs/solana-derivation-path"
version = "3.0.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derivation-path = { workspace = true }
qstring = { workspace = true }
uriparse = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
