[package]
name = "solana-pubkey"
description = "Solana account addresses"
documentation = "https://docs.rs/solana-pubkey"
version = "2.4.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
borsh = ["solana-address/borsh"]
bytemuck = ["solana-address/bytemuck"]
curve25519 = ["solana-address/curve25519"]
default = ["std"]
dev-context-only-utils = ["solana-address/dev-context-only-utils"]
frozen-abi = ["solana-address/frozen-abi"]
rand = ["dep:rand", "solana-address/rand"]
serde = ["solana-address/serde"]
sha2 = ["solana-address/sha2"]
std = ["solana-address/std"]

[dependencies]
rand = { workspace = true, optional = true }
solana-address = { workspace = true, features = ["atomic", "decode", "error", "sanitize", "sha2", "syscalls"] }

[lints]
workspace = true
