[package]
name = "solana-atomic-u64"
description = "Solana atomic u64 implementation. For internal use only."
documentation = "https://docs.rs/solana-atomic-u64"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[target.'cfg(not(target_pointer_width = "64"))'.dependencies]
parking_lot = { workspace = true }
