[package]
name = "solana-precompile-error"
description = "Solana PrecompileError type"
documentation = "https://docs.rs/solana-precompile-error"
version = "3.0.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
num-traits = { workspace = true }
