[package]
name = "solana-program-pack"
description = "Solana Pack serialization trait."
documentation = "https://docs.rs/solana-program-pack"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
solana-program-error = { workspace = true }
