[package]
name = "solana-feature-gate-interface"
description = "Solana feature gate program interface."
documentation = "https://docs.rs/solana-feature-gate-interface"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = "1.81.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
bincode = [
    "dep:bincode",
    "dep:solana-account",
    "dep:solana-account-info",
    "dep:solana-instruction",
    "dep:solana-rent",
    "dep:solana-system-interface",
    "serde",
]
dev-context-only-utils = ["bincode"]
serde = ["dep:serde", "dep:serde_derive"]

[dependencies]
bincode = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-account = { workspace = true, optional = true }
solana-account-info = { workspace = true, optional = true }
solana-instruction = { workspace = true, optional = true }
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true, optional = true }
solana-sdk-ids = { workspace = true }
solana-system-interface = { workspace = true, optional = true, features = [
    "bincode",
] }

[dev-dependencies]
solana-feature-gate-interface = { path = ".", features = ["dev-context-only-utils"] }
strum = { workspace = true }
strum_macros = { workspace = true }

[lints]
workspace = true
