[package]
name = "solana-signer"
description = "Abstractions for Solana transaction signers. See `solana-keypair` for a concrete implementation."
documentation = "https://docs.rs/solana-signer"
version = "3.0.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }
solana-transaction-error = { workspace = true }
