[package]
name = "solana-package-metadata"
description = "Solana Package Metadata"
documentation = "https://docs.rs/solana-package-metadata"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
solana-package-metadata-macro = { workspace = true }
solana-pubkey = { workspace = true }
